### Imports

In [70]:
import pandas as pd
import numpy as np
import fastf1 as fastf1
fastf1.Cache.enable_cache("../cache")
import fastf1.ergast as ergast
import datetime
import json
import time
import optuna
import matplotlib.pyplot as plt
import plotly.io as show


from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import GroupKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

from xgboost import XGBRanker

### 1. Basic Cleaning and splitting the dataset
#### 1.1 Reading in the Data and Inspection

In [71]:
raw_data = pd.read_csv("../data/driver_results_final.csv")

In [72]:
pd.set_option("display.max_columns", None)
raw_data.head()

,Round,Year,RaceName,MeetingKey,SessionKey,CircuitKey,CircuitShortName,StartDate,DriverNumber,FullName,Abbreviation,DriverId,TeamId,Position,GridPosition,ClassifiedPosition,Status,Points,Time,Laps,AirTemp,RainFall,WindSpeed,QualiTime,DriverPoints,ConstructorPoints,TeamAverageFinishEWMA,EWMAFinishPosition,relevance_score
0,1,2018,Australian Grand Prix,979,5066,10,Melbourne,2018-03-25 16:10:00,5,Sebastian Vettel,VET,vettel,ferrari,1.0,3.0,1,Finished,25.0,0 days 01:29:33.283000,58.0,24.077477,0.045045,3.691892,0 days 00:00:00.674000,25.0,40.0,0.0,0.0,22.0
1,1,2018,Australian Grand Prix,979,5066,10,Melbourne,2018-03-25 16:10:00,44,Lewis Hamilton,HAM,hamilton,mercedes,2.0,1.0,2,Finished,18.0,0 days 00:00:05.036000,58.0,24.077477,0.045045,3.691892,0 days 00:00:00,18.0,22.0,0.0,0.0,21.0
2,1,2018,Australian Grand Prix,979,5066,10,Melbourne,2018-03-25 16:10:00,7,Kimi Räikkönen,RAI,raikkonen,ferrari,3.0,2.0,3,Finished,15.0,0 days 00:00:06.309000,58.0,24.077477,0.045045,3.691892,0 days 00:00:00.664000,15.0,40.0,0.0,0.0,20.0
3,1,2018,Australian Grand Prix,979,5066,10,Melbourne,2018-03-25 16:10:00,3,Daniel Ricciardo,RIC,ricciardo,red_bull,4.0,8.0,4,Finished,12.0,0 days 00:00:07.069000,58.0,24.077477,0.045045,3.691892,0 days 00:00:00.988000,12.0,20.0,0.0,0.0,19.0
4,1,2018,Australian Grand Prix,979,5066,10,Melbourne,2018-03-25 16:10:00,14,Fernando Alonso,ALO,alonso,mclaren,5.0,10.0,5,Finished,10.0,0 days 00:00:27.886000,58.0,24.077477,0.045045,3.691892,0 days 00:00:02.433000,10.0,12.0,0.0,0.0,18.0

In [73]:
# Check for NaN / missing values
nan_mask = raw_data.isna()
print(f"Total NaNs in y: {nan_mask.sum()}")

Total NaNs in y: Round                    0
Year                     0
RaceName                 0
MeetingKey               0
SessionKey               0
CircuitKey               0
CircuitShortName         0
StartDate                0
DriverNumber             0
FullName                 0
Abbreviation             0
DriverId                 0
TeamId                   0
Position                 0
GridPosition             3
ClassifiedPosition       0
Status                   0
Points                   0
Time                     0
Laps                     0
AirTemp                  0
RainFall                 0
WindSpeed                0
QualiTime                0
DriverPoints             0
ConstructorPoints        0
TeamAverageFinishEWMA    0
EWMAFinishPosition       0
relevance_score          0
dtype: int64

#### 1.2 Data cleaning

In [74]:
data_df = raw_data.copy()

In [75]:
col_name = {
    'Round':"round",
    'Year':"year",
    'RaceName':"race_name",
    'MeetingKey':"meeting_key",
    'SessionKey':"session_key",
    'CircuitKey':"circuit_key",
    'CircuitShortName':"circuit_name",
    'StartDate':"start_date",
    'DriverNumber':"driver_number",
    'FullName':"full_name",
    'Abbreviation':"abv",
    'DriverId':"driver_id",
    'TeamId':"team_id",
    'Position':"finish_position",
    'GridPosition':"grid_position",
    'ClassifiedPosition':"classified_position",
    'Status':"status",
    'Points':"race_points",
    'Time':"race_finish_time",
    'Laps':"laps",
    'AirTemp':"air_temp",
    'RainFall':"rainfall",
    'WindSpeed':"wind_speed",
    'QualiTime':"quali_relative_time",
    'DriverPoints':"driver_points",
    'ConstructorPoints':"constructor_points",
    'TeamAverageFinishEWMA':"constructors_ewma",
    'EWMAFinishPosition':"driver_ewma",
    'relevance_score':"relevance_score"
}

data_df.rename(columns=col_name, inplace=True)

In [76]:
data_df.drop(['start_date','status','full_name','abv','race_points','meeting_key','circuit_name','circuit_key','round','race_name','driver_number','classified_position','finish_position','grid_position','laps','team_id','race_finish_time','driver_points', 'constructor_points'],axis=1,inplace=True)
data_df = data_df.sort_values(by=['year', 'session_key']).reset_index(drop=True)

In [77]:
data_df['quali_relative_time'] = pd.to_timedelta(data_df['quali_relative_time'])
#kind-off data scaling and encoding
data_df['quali_relative_time'] = data_df['quali_relative_time'].map(lambda x : ((x / datetime.timedelta(microseconds=1))/1000))

In [78]:
for col in ['constructors_ewma', 'driver_ewma']:
    data_df[col] = data_df[col].map(lambda x : 20.0 if pd.isna(x) else x)

In [79]:
for col in ['relevance_score']:
    data_df[col] = data_df[col].map(lambda x : 0.0 if pd.isna(x) else x)

#### 1.3 Splitting the Data

In [80]:
cleaned_df = data_df.copy()

In [81]:
#split and sort by session key after sort
train_mask = cleaned_df['year'] < 2024
test_mask = cleaned_df['year'] >= 2024

train_df = cleaned_df[train_mask]
test_df = cleaned_df[test_mask]

In [82]:
#sort data by session key
train_df = train_df.sort_values(by=['session_key'])
test_df = test_df.sort_values(by=['session_key'])

sorted_df = cleaned_df.sort_values(by=['session_key'])

In [83]:
y_train = train_df['relevance_score'].copy()
y_test = test_df['relevance_score'].copy()
y = sorted_df['relevance_score'].copy()
y.head()

0     22.0
19     3.0
18     4.0
17     5.0
16     6.0
Name: relevance_score, dtype: float64

In [84]:
X_train = train_df.copy()
X_train.drop(['relevance_score','year','session_key','driver_id'], axis=1, inplace=True)
X_train.head()

X_test = test_df.copy()
X = sorted_df.copy()
X.drop(['relevance_score','year','session_key', 'driver_id'], axis=1, inplace=True)
X.head()

one_session_mask = X_test['session_key'] == 11361


X_test.drop(['relevance_score','year','session_key','driver_id'], axis=1, inplace=True)
X_test.head()

,air_temp,rainfall,wind_speed,quali_relative_time,constructors_ewma,driver_ewma
2500,18.227389,0.0,0.785987,14.0,5.645641,1.007152
2519,18.227389,0.0,0.785987,1605.0,29.041414,15.350103
2518,18.227389,0.0,0.785987,1591.0,0.000000,17.732445
2517,18.227389,0.0,0.785987,1783.0,21.378545,11.578794
2516,18.227389,0.0,0.785987,1628.0,21.378545,9.799751

In [85]:
#extract the qid
qid_train = train_df.session_key.copy()

qid_test = test_df.session_key.copy()

qid = sorted_df.session_key.copy()
qid.head()

qid_train.head()

0     5066
19    5066
18    5066
17    5066
16    5066
Name: session_key, dtype: int64

In [86]:
print("--- TARGET DATA CHECK ---")
print("y_train min/max:", y_train.min(), y_train.max())
print("y_train NaNs:", y_train.isna().sum())

print("\n--- FEATURE DATA TYPES ---")
print(X_train.dtypes)

print("\n--- GROUP SIZE CHECK ---")
qid_series = pd.Series(qid_train)
print("Unique sessions:", qid_series.nunique())
print("Drivers per session (min/mean/max):", 
      qid_series.value_counts().min(),
      qid_series.value_counts().mean(),
      qid_series.value_counts().max())

--- TARGET DATA CHECK ---
y_train min/max: 3.0 22.0
y_train NaNs: 0

--- FEATURE DATA TYPES ---
air_temp               float64
rainfall               float64
wind_speed             float64
quali_relative_time    float64
constructors_ewma      float64
driver_ewma            float64
dtype: object

--- GROUP SIZE CHECK ---
Unique sessions: 125
Drivers per session (min/mean/max): 20 20.0 20

In [87]:
#Hyper-parameter tuning
# param_grid = {
#     'n_estimators' : [50,100,150,200,270],
#     'learning_rate' : [0.005,0.01,0.1,0.2],
#     'max_depth' : [3,5,7],
#     'max_leaves' : [5,7,10],
#     'grow_policy' : ['depthwise', 'lossguide'],
#     'min_child_weight': [1,2,3,5],
#     'subsample' : [0.65, 0.7, 0.8, 1.0],
#     'gamma' : [0.0, 0.1, 0.5, 1.0, 3.0],
#     'reg-alpha' : [0, 0.1, 1, 10, 100],
#     'reg_lambda' : [0.0,0.1,1.0,1.5],
#     'lambdarank_num_pair_per_sample' : [5,10,20] #needed?
# }

# ranker = XGBRanker(tree_method='exact', ndgc_exp_gain=False, lambdarank_unbiased=False, lambdarank_pair_method='mean', eval_metric='ndgc',  objective="rank:ndcg")

# gkf = GroupKFold(n_splits=10)

# grid_search = RandomizedSearchCV(estimator=ranker, param_distributions=param_grid, n_iter=150, n_jobs=-1, cv=gkf, verbose=2, random_state=63, scoring='accuracy')
# grid_search.fit(X_train, y_train,)

# print("best param :", grid_search.best_params_)
# print("best accuracy :", grid_search.best_score_)

In [88]:
#using optuna to hyperparameterize
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial):
    param_grid = {
    'n_estimators' : trial.suggest_int('n_estimators',50,500),
    'learning_rate': trial.suggest_float("learning_rate", 0.005, 0.2, log=True),
    'max_depth' : trial.suggest_int('max_depth',3,10),
    'max_leaves' : trial.suggest_int('max_leaves',5,30),
    "objective": "rank:ndcg",
    "eval_metric": "ndcg",
    'early_stopping_rounds' : 30,
    "tree_method": "exact",
    "ndcg_exp_gain" : False,
    "lambdarank_unbiased" : False,
    "lambdarank_pair_method" : 'mean',
    "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
    "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
    "subsample": trial.suggest_float("subsample", 0.6, 1.0),
    "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
    'min_child_weight': trial.suggest_int('min_child_weight', 1, 6),
    "gamma": trial.suggest_float("gamma", 0.0, 3.0)
    #'lambdarank_num_pair_per_sample' : [5,10,20] #needed?
    }

    gkf = GroupKFold(n_splits=5)
    cv_scores = []

    for train_idx, val_idx in gkf.split(X, y, groups=qid):
        model = XGBRanker(**param_grid)
        model.fit(
            X.iloc[train_idx],
            y.iloc[train_idx],
            qid=qid.iloc[train_idx],
            eval_set=[(X.iloc[val_idx], y.iloc[val_idx])],
            eval_qid=[qid.iloc[val_idx]],
            verbose=2,
        )
        
        cv_scores.append(model.best_score)

    return np.mean(cv_scores)

In [89]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=50)

[0]	validation_0-ndcg:0.86319
[2]	validation_0-ndcg:0.92678
[4]	validation_0-ndcg:0.93500
[6]	validation_0-ndcg:0.93931
[8]	validation_0-ndcg:0.93916
[10]	validation_0-ndcg:0.94125
[12]	validation_0-ndcg:0.94216
[14]	validation_0-ndcg:0.94257
[16]	validation_0-ndcg:0.94340
[18]	validation_0-ndcg:0.94386
[20]	validation_0-ndcg:0.94531
[22]	validation_0-ndcg:0.94569
[24]	validation_0-ndcg:0.94516
[26]	validation_0-ndcg:0.94538
[28]	validation_0-ndcg:0.94572
[30]	validation_0-ndcg:0.94650
[32]	validation_0-ndcg:0.94625
[34]	validation_0-ndcg:0.94593
[36]	validation_0-ndcg:0.94548
[38]	validation_0-ndcg:0.94568
[40]	validation_0-ndcg:0.94638
[42]	validation_0-ndcg:0.94686
[44]	validation_0-ndcg:0.94696
[46]	validation_0-ndcg:0.94713
[48]	validation_0-ndcg:0.94666
[50]	validation_0-ndcg:0.94620
[52]	validation_0-ndcg:0.94698
[54]	validation_0-ndcg:0.94672
[56]	validation_0-ndcg:0.94691
[58]	validation_0-ndcg:0.94685
[60]	validation_0-ndcg:0.94672
[62]	validation_0-ndcg:0.94690
[64]	validation_0-ndcg:0.94695
[66]	validation_0-ndcg:0.94712
[68]	validation_0-ndcg:0.94707
[70]	validation_0-ndcg:0.94705
[72]	validation_0-ndcg:0.94684
[74]	validation_0-ndcg:0.94680
[76]	validation_0-ndcg:0.94661
[0]	validation_0-ndcg:0.88635
[2]	validation_0-ndcg:0.94495
[4]	validation_0-ndcg:0.94861
[6]	validation_0-ndcg:0.95353
[8]	validation_0-ndcg:0.95609
[10]	validation_0-ndcg:0.95752
[12]	validation_0-ndcg:0.95823
[14]	validation_0-ndcg:0.95787
[16]	validation_0-ndcg:0.95757
[18]	validation_0-ndcg:0.95680
[20]	validation_0-ndcg:0.95661
[22]	validation_0-ndcg:0.95720
[24]	validation_0-ndcg:0.95616
[26]	validation_0-ndcg:0.95642
[28]	validation_0-ndcg:0.95596
[30]	validation_0-ndcg:0.95479
[32]	validation_0-ndcg:0.95505
[34]	validation_0-ndcg:0.95454
[36]	validation_0-ndcg:0.95461
[38]	validation_0-ndcg:0.95484
[40]	validation_0-ndcg:0.95503
[42]	validation_0-ndcg:0.95486
[43]	validation_0-ndcg:0.95479
[0]	validation_0-ndcg:0.85978
[2]	validation_0-ndcg:0.94348
[4]	validation_0-ndcg:0.94577
[6]	validation_0-ndcg:0.94403
[8]	validation_0-ndcg:0.94301
[10]	validation_0-ndcg:0.94325
[12]	validation_0-ndcg:0.94445
[14]	validation_0-ndcg:0.94283
[16]	validation_0-ndcg:0.94362
[18]	validation_0-ndcg:0.94248
[20]	validation_0-ndcg:0.94353
[22]	validation_0-ndcg:0.94367
[24]	validation_0-ndcg:0.94274
[26]	validation_0-ndcg:0.94263
[28]	validation_0-ndcg:0.94077
[30]	validation_0-ndcg:0.94135
[32]	validation_0-ndcg:0.94198
[34]	validation_0-ndcg:0.94337
[36]	validation_0-ndcg:0.94318
[38]	validation_0-ndcg:0.94253
[40]	validation_0-ndcg:0.94253
[42]	validation_0-ndcg:0.94241
[43]	validation_0-ndcg:0.94237
[0]	validation_0-ndcg:0.85300
[2]	validation_0-ndcg:0.93530
[4]	validation_0-ndcg:0.94169
[6]	validation_0-ndcg:0.94299
[8]	validation_0-ndcg:0.94578
[10]	validation_0-ndcg:0.94800
[12]	validation_0-ndcg:0.94700
[14]	validation_0-ndcg:0.94809
[16]	validation_0-ndcg:0.94834
[18]	validation_0-ndcg:0.94730
[20]	validation_0-ndcg:0.94873
[22]	validation_0-ndcg:0.94772
[24]	validation_0-ndcg:0.95047
[26]	validation_0-ndcg:0.95117
[28]	validation_0-ndcg:0.94955
[30]	validation_0-ndcg:0.94863
[32]	validation_0-ndcg:0.94870
[34]	validation_0-ndcg:0.94897
[36]	validation_0-ndcg:0.94929
[38]	validation_0-ndcg:0.94949
[40]	validation_0-ndcg:0.95013
[42]	validation_0-ndcg:0.94985
[44]	validation_0-ndcg:0.94984
[46]	validation_0-ndcg:0.94996
[48]	validation_0-ndcg:0.95004
[50]	validation_0-ndcg:0.94942
[52]	validation_0-ndcg:0.95009
[54]	validation_0-ndcg:0.94950
[56]	validation_0-ndcg:0.95000
[0]	validation_0-ndcg:0.83589
[2]	validation_0-ndcg:0.93986
[4]	validation_0-ndcg:0.94437
[6]	validation_0-ndcg:0.94578
[8]	validation_0-ndcg:0.94627
[10]	validation_0-ndcg:0.94677
[12]	validation_0-ndcg:0.94655
[14]	validation_0-ndcg:0.94781
[16]	validation_0-ndcg:0.94958
[18]	validation_0-ndcg:0.94925
[20]	validation_0-ndcg:0.94862
[22]	validation_0-ndcg:0.94862
[24]	validation_0-ndcg:0.94889
[26]	validation_0-ndcg:0.94917
[28]	validation_0-ndcg:0.94898
[30]	validation_0-ndcg:0.94913
[32]	validation_0-ndcg:0.95181
[34]	validation_0-ndcg:0.95062
[36]	validation_0-ndcg:0.95028
[38]	validation_0-ndcg:0.95214
[40]	validation_0-ndcg:0.95230
[42]	validation_0-ndcg:0.95226
[44]	validation_0-ndcg:0.95245
[46]	validation_0-ndcg:0.95225
[48]	validation_0-ndcg:0.95246
[50]	validation_0-ndcg:0.95249
[52]	validation_0-ndcg:0.95315
[54]	validation_0-ndcg:0.95304
[56]	validation_0-ndcg:0.95281
[58]	validation_0-ndcg:0.95274
[60]	validation_0-ndcg:0.95275
[62]	validation_0-ndcg:0.95216
[64]	validation_0-ndcg:0.95219
[66]	validation_0-ndcg:0.95219
[68]	validation_0-ndcg:0.95225
[70]	validation_0-ndcg:0.95225
[72]	validation_0-ndcg:0.95236
[74]	validation_0-ndcg:0.95215
[76]	validation_0-ndcg:0.95211
[78]	validation_0-ndcg:0.95253
[80]	validation_0-ndcg:0.95253
[82]	validation_0-ndcg:0.95249
[83]	validation_0-ndcg:0.95252
[0]	validation_0-ndcg:0.87073
[2]	validation_0-ndcg:0.93764
[4]	validation_0-ndcg:0.94135
[6]	validation_0-ndcg:0.94282
[8]	validation_0-ndcg:0.94172
[10]	validation_0-ndcg:0.94155
[12]	validation_0-ndcg:0.94287
[14]	validation_0-ndcg:0.94323
[16]	validation_0-ndcg:0.94494
[18]	validation_0-ndcg:0.94502
[20]	validation_0-ndcg:0.94505
[22]	validation_0-ndcg:0.94352
[24]	validation_0-ndcg:0.94551
[26]	validation_0-ndcg:0.94573
[28]	validation_0-ndcg:0.94544
[30]	validation_0-ndcg:0.94542
[32]	validation_0-ndcg:0.94566
[34]	validation_0-ndcg:0.94555
[36]	validation_0-ndcg:0.94529
[38]	validation_0-ndcg:0.94547
[40]	validation_0-ndcg:0.94575
[42]	validation_0-ndcg:0.94594
[44]	validation_0-ndcg:0.94556
[46]	validation_0-ndcg:0.94552
[48]	validation_0-ndcg:0.94544
[50]	validation_0-ndcg:0.94566
[52]	validation_0-ndcg:0.94570
[54]	validation_0-ndcg:0.94669
[56]	validation_0-ndcg:0.94675
[58]	validation_0-ndcg:0.94657
[60]	validation_0-ndcg:0.94657
[62]	validation_0-ndcg:0.94689
[64]	validation_0-ndcg:0.94680
[66]	validation_0-ndcg:0.94637
[68]	validation_0-ndcg:0.94647
[70]	validation_0-ndcg:0.94620
[72]	validation_0-ndcg:0.94608
[74]	validation_0-ndcg:0.94615
[76]	validation_0-ndcg:0.94587
[78]	validation_0-ndcg:0.94603
[80]	validation_0-ndcg:0.94607
[82]	validation_0-ndcg:0.94603
[84]	validation_0-ndcg:0.94603
[86]	validation_0-ndcg:0.94606
[88]	validation_0-ndcg:0.94606
[90]	validation_0-ndcg:0.94607
[92]	validation_0-ndcg:0.94610
[93]	validation_0-ndcg:0.94610
[0]	validation_0-ndcg:0.88635
[2]	validation_0-ndcg:0.94331
[4]	validation_0-ndcg:0.94531
[6]	validation_0-ndcg:0.95148
[8]	validation_0-ndcg:0.95432
[10]	validation_0-ndcg:0.95450
[12]	validation_0-ndcg:0.95474
[14]	validation_0-ndcg:0.95299
[16]	validation_0-ndcg:0.95329
[18]	validation_0-ndcg:0.95365
[20]	validation_0-ndcg:0.95430
[22]	validation_0-ndcg:0.95461
[24]	validation_0-ndcg:0.95465
[26]	validation_0-ndcg:0.95535
[28]	validation_0-ndcg:0.95532
[30]	validation_0-ndcg:0.95581
[32]	validation_0-ndcg:0.95636
[34]	validation_0-ndcg:0.95619
[36]	validation_0-ndcg:0.95629
[38]	validation_0-ndcg:0.95627
[40]	validation_0-ndcg:0.95644
[42]	validation_0-ndcg:0.95511
[44]	validation_0-ndcg:0.95523
[46]	validation_0-ndcg:0.95596
[48]	validation_0-ndcg:0.95602
[50]	validation_0-ndcg:0.95595
[52]	validation_0-ndcg:0.95573
[54]	validation_0-ndcg:0.95595
[56]	validation_0-ndcg:0.95606
[58]	validation_0-ndcg:0.95595
[60]	validation_0-ndcg:0.95576
[62]	validation_0-ndcg:0.95584
[63]	validation_0-ndcg:0.95577
[0]	validation_0-ndcg:0.85861
[2]	validation_0-ndcg:0.92596
[4]	validation_0-ndcg:0.93548
[6]	validation_0-ndcg:0.94091
[8]	validation_0-ndcg:0.94118
[10]	validation_0-ndcg:0.94335
[12]	validation_0-ndcg:0.94373
[14]	validation_0-ndcg:0.94387
[16]	validation_0-ndcg:0.94432
[18]	validation_0-ndcg:0.94438
[20]	validation_0-ndcg:0.94522
[22]	validation_0-ndcg:0.94510
[24]	validation_0-ndcg:0.94477
[26]	validation_0-ndcg:0.94492
[28]	validation_0-ndcg:0.94508
[30]	validation_0-ndcg:0.94525
[32]	validation_0-ndcg:0.94567
[34]	validation_0-ndcg:0.94572
[36]	validation_0-ndcg:0.94585
[38]	validation_0-ndcg:0.94553
[40]	validation_0-ndcg:0.94396
[42]	validation_0-ndcg:0.94394
[44]	validation_0-ndcg:0.94412
[46]	validation_0-ndcg:0.94409
[48]	validation_0-ndcg:0.94428
[50]	validation_0-ndcg:0.94694
[52]	validation_0-ndcg:0.94703
[54]	validation_0-ndcg:0.94691
[56]	validation_0-ndcg:0.94697
[58]	validation_0-ndcg:0.94899
[60]	validation_0-ndcg:0.94889
[62]	validation_0-ndcg:0.94899
[64]	validation_0-ndcg:0.94911
[66]	validation_0-ndcg:0.94865
[68]	validation_0-ndcg:0.94863
[70]	validation_0-ndcg:0.94865
[72]	validation_0-ndcg:0.94863
[74]	validation_0-ndcg:0.94863
[76]	validation_0-ndcg:0.94856
[78]	validation_0-ndcg:0.94859
[80]	validation_0-ndcg:0.94854
[82]	validation_0-ndcg:0.94847
[84]	validation_0-ndcg:0.94670
[86]	validation_0-ndcg:0.94868
[88]	validation_0-ndcg:0.94873
[90]	validation_0-ndcg:0.94695
[92]	validation_0-ndcg:0.94673
[93]	validation_0-ndcg:0.94673
[0]	validation_0-ndcg:0.85300
[2]	validation_0-ndcg:0.93555
[4]	validation_0-ndcg:0.94048
[6]	validation_0-ndcg:0.94789
[8]	validation_0-ndcg:0.95011
[10]	validation_0-ndcg:0.95038
[12]	validation_0-ndcg:0.95160
[14]	validation_0-ndcg:0.94940
[16]	validation_0-ndcg:0.94951
[18]	validation_0-ndcg:0.95161
[20]	validation_0-ndcg:0.95211
[22]	validation_0-ndcg:0.95224
[24]	validation_0-ndcg:0.95150
[26]	validation_0-ndcg:0.95229
[28]	validation_0-ndcg:0.95277
[30]	validation_0-ndcg:0.95177
[32]	validation_0-ndcg:0.95228
[34]	validation_0-ndcg:0.95229
[36]	validation_0-ndcg:0.95231
[38]	validation_0-ndcg:0.95283
[40]	validation_0-ndcg:0.95292
[42]	validation_0-ndcg:0.95287
[44]	validation_0-ndcg:0.95286
[46]	validation_0-ndcg:0.95298
[48]	validation_0-ndcg:0.95296
[50]	validation_0-ndcg:0.95325
[52]	validation_0-ndcg:0.95314
[54]	validation_0-ndcg:0.95350
[56]	validation_0-ndcg:0.95343
[58]	validation_0-ndcg:0.95332
[60]	validation_0-ndcg:0.95320
[62]	validation_0-ndcg:0.95312
[64]	validation_0-ndcg:0.95342
[66]	validation_0-ndcg:0.95314
[68]	validation_0-ndcg:0.95317
[70]	validation_0-ndcg:0.95303
[72]	validation_0-ndcg:0.95305
[74]	validation_0-ndcg:0.95357
[76]	validation_0-ndcg:0.95299
[78]	validation_0-ndcg:0.95299
[80]	validation_0-ndcg:0.95310
[82]	validation_0-ndcg:0.95275
[84]	validation_0-ndcg:0.95275
[86]	validation_0-ndcg:0.95274
[88]	validation_0-ndcg:0.95274
[90]	validation_0-ndcg:0.95302
[92]	validation_0-ndcg:0.95307
[94]	validation_0-ndcg:0.95307
[96]	validation_0-ndcg:0.95307
[98]	validation_0-ndcg:0.95256
[100]	validation_0-ndcg:0.95256
[102]	validation_0-ndcg:0.95272
[104]	validation_0-ndcg:0.95272
[0]	validation_0-ndcg:0.84538
[2]	validation_0-ndcg:0.94770
[4]	validation_0-ndcg:0.94867
[6]	validation_0-ndcg:0.95187
[8]	validation_0-ndcg:0.95419
[10]	validation_0-ndcg:0.95438
[12]	validation_0-ndcg:0.95374
[14]	validation_0-ndcg:0.95212
[16]	validation_0-ndcg:0.95205
[18]	validation_0-ndcg:0.95189
[20]	validation_0-ndcg:0.95153
[22]	validation_0-ndcg:0.95181
[24]	validation_0-ndcg:0.95085
[26]	validation_0-ndcg:0.94997
[28]	validation_0-ndcg:0.94901
[30]	validation_0-ndcg:0.94899
[32]	validation_0-ndcg:0.94884
[34]	validation_0-ndcg:0.94912
[36]	validation_0-ndcg:0.94934
[37]	validation_0-ndcg:0.94918
[0]	validation_0-ndcg:0.87335
[2]	validation_0-ndcg:0.92924
[4]	validation_0-ndcg:0.93574
[6]	validation_0-ndcg:0.94474
[8]	validation_0-ndcg:0.94618
[10]	validation_0-ndcg:0.94647
[12]	validation_0-ndcg:0.94652
[14]	validation_0-ndcg:0.94690
[16]	validation_0-ndcg:0.94550
[18]	validation_0-ndcg:0.94567
[20]	validation_0-ndcg:0.94554
[22]	validation_0-ndcg:0.94598
[24]	validation_0-ndcg:0.94555
[26]	validation_0-ndcg:0.94578
[28]	validation_0-ndcg:0.94607
[30]	validation_0-ndcg:0.94675
[32]	validation_0-ndcg:0.94701
[34]	validation_0-ndcg:0.94674
[36]	validation_0-ndcg:0.94708
[38]	validation_0-ndcg:0.94800
[40]	validation_0-ndcg:0.94758
[42]	validation_0-ndcg:0.94779
[44]	validation_0-ndcg:0.94807
[46]	validation_0-ndcg:0.94827
[48]	validation_0-ndcg:0.94830
[50]	validation_0-ndcg:0.94840
[52]	validation_0-ndcg:0.94867
[54]	validation_0-ndcg:0.94902
[56]	validation_0-ndcg:0.94899
[58]	validation_0-ndcg:0.94860
[60]	validation_0-ndcg:0.94864
[62]	validation_0-ndcg:0.94878
[64]	validation_0-ndcg:0.94863
[66]	validation_0-ndcg:0.94861
[68]	validation_0-ndcg:0.94864
[70]	validation_0-ndcg:0.94857
[72]	validation_0-ndcg:0.94858
[74]	validation_0-ndcg:0.94853
[76]	validation_0-ndcg:0.94856
[78]	validation_0-ndcg:0.94871
[80]	validation_0-ndcg:0.94882
[82]	validation_0-ndcg:0.94882
[84]	validation_0-ndcg:0.94897
[85]	validation_0-ndcg:0.94895
[0]	validation_0-ndcg:0.89746
[2]	validation_0-ndcg:0.94994
[4]	validation_0-ndcg:0.95193
[6]	validation_0-ndcg:0.96093
[8]	validation_0-ndcg:0.95682
[10]	validation_0-ndcg:0.95831
[12]	validation_0-ndcg:0.95700
[14]	validation_0-ndcg:0.95809
[16]	validation_0-ndcg:0.95664
[18]	validation_0-ndcg:0.95760
[20]	validation_0-ndcg:0.95763
[22]	validation_0-ndcg:0.95867
[24]	validation_0-ndcg:0.95870
[26]	validation_0-ndcg:0.95887
[28]	validation_0-ndcg:0.95843
[30]	validation_0-ndcg:0.95855
[32]	validation_0-ndcg:0.95882
[34]	validation_0-ndcg:0.95897
[36]	validation_0-ndcg:0.95900
[0]	validation_0-ndcg:0.85405
[2]	validation_0-ndcg:0.93182
[4]	validation_0-ndcg:0.93239
[6]	validation_0-ndcg:0.93928
[8]	validation_0-ndcg:0.94242
[10]	validation_0-ndcg:0.94240
[12]	validation_0-ndcg:0.94129
[14]	validation_0-ndcg:0.94368
[16]	validation_0-ndcg:0.94430
[18]	validation_0-ndcg:0.94460
[20]	validation_0-ndcg:0.94469
[22]	validation_0-ndcg:0.94498
[24]	validation_0-ndcg:0.94394
[26]	validation_0-ndcg:0.94394
[28]	validation_0-ndcg:0.94408
[30]	validation_0-ndcg:0.94418
[32]	validation_0-ndcg:0.94498
[34]	validation_0-ndcg:0.94573
[36]	validation_0-ndcg:0.94568
[38]	validation_0-ndcg:0.94616
[40]	validation_0-ndcg:0.94625
[42]	validation_0-ndcg:0.94605
[44]	validation_0-ndcg:0.94594
[46]	validation_0-ndcg:0.94619
[48]	validation_0-ndcg:0.94821
[50]	validation_0-ndcg:0.94664
[52]	validation_0-ndcg:0.94601
[54]	validation_0-ndcg:0.94592
[56]	validation_0-ndcg:0.94597
[58]	validation_0-ndcg:0.94700
[60]	validation_0-ndcg:0.94713
[62]	validation_0-ndcg:0.94706
[64]	validation_0-ndcg:0.94886
[66]	validation_0-ndcg:0.94891
[68]	validation_0-ndcg:0.94903
[70]	validation_0-ndcg:0.94914
[72]	validation_0-ndcg:0.94737
[74]	validation_0-ndcg:0.94795
[76]	validation_0-ndcg:0.94745
[78]	validation_0-ndcg:0.94743
[80]	validation_0-ndcg:0.94746
[82]	validation_0-ndcg:0.94746
[84]	validation_0-ndcg:0.94796
[86]	validation_0-ndcg:0.94796
[88]	validation_0-ndcg:0.94795
[90]	validation_0-ndcg:0.94801
[92]	validation_0-ndcg:0.94801
[94]	validation_0-ndcg:0.94799
[96]	validation_0-ndcg:0.94806
[98]	validation_0-ndcg:0.94797
[100]	validation_0-ndcg:0.94796
[0]	validation_0-ndcg:0.87995
[2]	validation_0-ndcg:0.94400
[4]	validation_0-ndcg:0.94597
[6]	validation_0-ndcg:0.94747
[8]	validation_0-ndcg:0.94905
[10]	validation_0-ndcg:0.95074
[12]	validation_0-ndcg:0.95120
[14]	validation_0-ndcg:0.95103
[16]	validation_0-ndcg:0.95109
[18]	validation_0-ndcg:0.95190
[20]	validation_0-ndcg:0.95175
[22]	validation_0-ndcg:0.95217
[24]	validation_0-ndcg:0.95206
[26]	validation_0-ndcg:0.95215
[28]	validation_0-ndcg:0.95196
[30]	validation_0-ndcg:0.95219
[32]	validation_0-ndcg:0.95275
[34]	validation_0-ndcg:0.95215
[36]	validation_0-ndcg:0.95194
[38]	validation_0-ndcg:0.95206
[40]	validation_0-ndcg:0.95193
[42]	validation_0-ndcg:0.95255
[44]	validation_0-ndcg:0.95259
[46]	validation_0-ndcg:0.95247
[48]	validation_0-ndcg:0.95221
[50]	validation_0-ndcg:0.95226
[52]	validation_0-ndcg:0.95236
[54]	validation_0-ndcg:0.95233
[56]	validation_0-ndcg:0.95228
[58]	validation_0-ndcg:0.95177
[60]	validation_0-ndcg:0.95241
[62]	validation_0-ndcg:0.95193
[0]	validation_0-ndcg:0.86350
[2]	validation_0-ndcg:0.94290
[4]	validation_0-ndcg:0.94814
[6]	validation_0-ndcg:0.95023
[8]	validation_0-ndcg:0.95130
[10]	validation_0-ndcg:0.95252
[12]	validation_0-ndcg:0.95332
[14]	validation_0-ndcg:0.95148
[16]	validation_0-ndcg:0.95157
[18]	validation_0-ndcg:0.95378
[20]	validation_0-ndcg:0.95360
[22]	validation_0-ndcg:0.95294
[24]	validation_0-ndcg:0.95348
[26]	validation_0-ndcg:0.95310
[28]	validation_0-ndcg:0.95331
[30]	validation_0-ndcg:0.95337
[32]	validation_0-ndcg:0.95214
[34]	validation_0-ndcg:0.95035
[36]	validation_0-ndcg:0.95001
[38]	validation_0-ndcg:0.94957
[40]	validation_0-ndcg:0.94998
[42]	validation_0-ndcg:0.95064
[43]	validation_0-ndcg:0.95072
[0]	validation_0-ndcg:0.86319
[2]	validation_0-ndcg:0.92662
[4]	validation_0-ndcg:0.93813
[6]	validation_0-ndcg:0.93836
[8]	validation_0-ndcg:0.93973
[10]	validation_0-ndcg:0.94100
[12]	validation_0-ndcg:0.94253
[14]	validation_0-ndcg:0.94297
[16]	validation_0-ndcg:0.94304
[18]	validation_0-ndcg:0.94304
[20]	validation_0-ndcg:0.94254
[22]	validation_0-ndcg:0.94254
[24]	validation_0-ndcg:0.94254
[26]	validation_0-ndcg:0.94369
[28]	validation_0-ndcg:0.94397
[30]	validation_0-ndcg:0.94397
[32]	validation_0-ndcg:0.94426
[34]	validation_0-ndcg:0.94426
[36]	validation_0-ndcg:0.94426
[38]	validation_0-ndcg:0.94426
[40]	validation_0-ndcg:0.94426
[42]	validation_0-ndcg:0.94426
[44]	validation_0-ndcg:0.94426
[46]	validation_0-ndcg:0.94426
[48]	validation_0-ndcg:0.94426
[50]	validation_0-ndcg:0.94426
[52]	validation_0-ndcg:0.94426
[54]	validation_0-ndcg:0.94426
[56]	validation_0-ndcg:0.94426
[58]	validation_0-ndcg:0.94426
[60]	validation_0-ndcg:0.94426
[62]	validation_0-ndcg:0.94410
[0]	validation_0-ndcg:0.88569
[2]	validation_0-ndcg:0.94905
[4]	validation_0-ndcg:0.94841
[6]	validation_0-ndcg:0.95236
[8]	validation_0-ndcg:0.95695
[10]	validation_0-ndcg:0.95768
[12]	validation_0-ndcg:0.95759
[14]	validation_0-ndcg:0.95779
[16]	validation_0-ndcg:0.95788
[18]	validation_0-ndcg:0.95870
[20]	validation_0-ndcg:0.95870
[22]	validation_0-ndcg:0.95850
[24]	validation_0-ndcg:0.95850
[26]	validation_0-ndcg:0.95887
[28]	validation_0-ndcg:0.95887
[30]	validation_0-ndcg:0.95887
[32]	validation_0-ndcg:0.96112
[34]	validation_0-ndcg:0.95936
[36]	validation_0-ndcg:0.95936
[38]	validation_0-ndcg:0.95936
[40]	validation_0-ndcg:0.95936
[42]	validation_0-ndcg:0.95936
[44]	validation_0-ndcg:0.95951
[46]	validation_0-ndcg:0.95951
[48]	validation_0-ndcg:0.95951
[50]	validation_0-ndcg:0.95951
[52]	validation_0-ndcg:0.95951
[54]	validation_0-ndcg:0.95951
[56]	validation_0-ndcg:0.95951
[58]	validation_0-ndcg:0.95951
[60]	validation_0-ndcg:0.95951
[61]	validation_0-ndcg:0.95951
[0]	validation_0-ndcg:0.85683
[2]	validation_0-ndcg:0.94001
[4]	validation_0-ndcg:0.93753
[6]	validation_0-ndcg:0.93578
[8]	validation_0-ndcg:0.93711
[10]	validation_0-ndcg:0.93976
[12]	validation_0-ndcg:0.93809
[14]	validation_0-ndcg:0.94023
[16]	validation_0-ndcg:0.94326
[18]	validation_0-ndcg:0.94320
[20]	validation_0-ndcg:0.94539
[22]	validation_0-ndcg:0.94539
[24]	validation_0-ndcg:0.94515
[26]	validation_0-ndcg:0.94515
[28]	validation_0-ndcg:0.94515
[30]	validation_0-ndcg:0.94515
[32]	validation_0-ndcg:0.94550
[34]	validation_0-ndcg:0.94550
[36]	validation_0-ndcg:0.94550
[38]	validation_0-ndcg:0.94550
[40]	validation_0-ndcg:0.94550
[42]	validation_0-ndcg:0.94570
[44]	validation_0-ndcg:0.94632
[46]	validation_0-ndcg:0.94632
[48]	validation_0-ndcg:0.94639
[50]	validation_0-ndcg:0.94639
[52]	validation_0-ndcg:0.94639
[54]	validation_0-ndcg:0.94639
[56]	validation_0-ndcg:0.94639
[58]	validation_0-ndcg:0.94549
[60]	validation_0-ndcg:0.94549
[62]	validation_0-ndcg:0.94549
[64]	validation_0-ndcg:0.94549
[66]	validation_0-ndcg:0.94549
[68]	validation_0-ndcg:0.94549
[70]	validation_0-ndcg:0.94549
[72]	validation_0-ndcg:0.94529
[74]	validation_0-ndcg:0.94529
[76]	validation_0-ndcg:0.94529
[77]	validation_0-ndcg:0.94529
[0]	validation_0-ndcg:0.85300
[2]	validation_0-ndcg:0.93321
[4]	validation_0-ndcg:0.94242
[6]	validation_0-ndcg:0.94268
[8]	validation_0-ndcg:0.94520
[10]	validation_0-ndcg:0.94595
[12]	validation_0-ndcg:0.94826
[14]	validation_0-ndcg:0.94847
[16]	validation_0-ndcg:0.94847
[18]	validation_0-ndcg:0.94847
[20]	validation_0-ndcg:0.94915
[22]	validation_0-ndcg:0.94915
[24]	validation_0-ndcg:0.94694
[26]	validation_0-ndcg:0.94947
[28]	validation_0-ndcg:0.94947
[30]	validation_0-ndcg:0.94947

In [90]:
best_param = study.best_params
print(study.best_params)
print(study.best_value)

{'n_estimators': 96, 'learning_rate': 0.014327766729298533, 'max_depth': 5, 'max_leaves': 11, 'reg_alpha': 0.0035401431789771516, 'reg_lambda': 0.004520715924780918, 'subsample': 0.7684184054295675, 'colsample_bytree': 0.9318761708581184, 'min_child_weight': 4, 'gamma': 1.6432477526172597}
0.9540804791921766

In [94]:
fig = optuna.visualization.plot_optimization_history(study)
show.show(fig)

In [ ]:

ranker = XGBRanker(tree_method = 'hist', objective="rank:ndcg", learning_rate=0.05, max_depth=6, n_estimators=100 ,ndcg_exp_gain=False)
ranker.fit(X_train, y_train,qid=qid_train)

XGBRanker(base_score=None, booster=None, callbacks=None, colsample_bylevel=None,
          colsample_bynode=None, colsample_bytree=None, device=None,
          early_stopping_rounds=None, enable_categorical=True, eval_metric=None,
          feature_types=None, feature_weights=None, gamma=None,
          grow_policy=None, importance_type=None, interaction_constraints=None,
          learning_rate=0.05, max_bin=None, max_cat_threshold=None,
          max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
          max_leaves=None, min_child_weight=None, missing=nan,
          monotone_constraints=None, multi_strategy=None, n_estimators=100,
          n_jobs=None, ndcg_exp_gain=False, ...)

In [ ]:
print(ranker.feature_importances_)
print(y_train.value_counts())
print(qid_train.dtypes)
print(pd.Series(qid_train).value_counts().head())

[0.04042294 0.04984919 0.04329793 0.3063513  0.38647905 0.05941573
 0.06848595 0.04569793]
relevance_score
22.0    125
3.0     125
15.0    125
16.0    125
21.0    125
18.0    125
19.0    125
20.0    125
13.0    125
14.0    125
8.0     125
12.0    125
11.0    125
10.0    125
9.0     125
7.0     125
6.0     125
5.0     125
4.0     125
17.0    125
Name: count, dtype: int64
int64
session_key
5066    20
6714    20
7128    20
7115    20
7105    20
Name: count, dtype: int64

In [ ]:
cols_eval = ['air_temp', 'rainfall', 'wind_speed', 'quali_relative_time', 'driver_points', 'constructor_points', 'constructors_ewma', 'driver_ewma']
one_session = test_df[one_session_mask].copy()
one_session.info()
one_session.insert(0,'prediction',ranker.predict(one_session[cols_eval]))
one_session.sort_values(by='prediction', ascending=False)

<class 'pandas.core.frame.DataFrame'>
Index: 22 entries, 3735 to 3732
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 22 non-null     int64
 1   session_key          22 non-null     int64
 2   driver_id            22 non-null     object
 3   air_temp             22 non-null     float64
 4   rainfall             22 non-null     float64
 5   wind_speed           22 non-null     float64
 6   quali_relative_time  22 non-null     float64
 7   driver_points        22 non-null     float64
 8   constructor_points   22 non-null     float64
 9   constructors_ewma    22 non-null     float64
 10  driver_ewma          22 non-null     float64
 11  relevance_score      22 non-null     float64
dtypes: float64(9), int64(2), object(1)
memory usage: 2.2+ KB

,prediction,year,session_key,driver_id,air_temp,rainfall,wind_speed,quali_relative_time,driver_points,constructor_points,constructors_ewma,driver_ewma,relevance_score
3722,2.109710,2026,11361,antonelli,32.172727,0.0,1.347159,96.0,267.0,468.0,8.914423,2.901710,22.0
3727,1.065528,2026,11361,hamilton,32.172727,0.0,1.347159,225.0,191.0,346.0,8.623929,4.182677,17.0
3743,0.982414,2026,11361,leclerc,32.172727,0.0,1.347159,218.0,155.0,346.0,8.623929,4.441252,1.0
3728,0.815895,2026,11361,gasly,32.172727,0.0,1.347159,0.0,41.0,62.0,24.166822,10.628091,16.0
3723,0.771289,2026,11361,russell,32.172727,0.0,1.347159,60.0,201.0,468.0,8.914423,6.012713,21.0
3725,0.724279,2026,11361,norris,32.172727,0.0,1.347159,281.0,171.0,287.0,11.575531,2.047086,19.0
3724,0.716789,2026,11361,max_verstappen,32.172727,0.0,1.347159,284.0,127.0,204.0,20.789975,14.275392,20.0
3726,0.659158,2026,11361,piastri,32.172727,0.0,1.347159,180.0,116.0,287.0,11.575531,9.528445,18.0
3735,0.269555,2026,11361,lawson,32.172727,0.0,1.347159,1035.0,51.0,204.0,20.789975,7.795594,9.0
3729,0.248204,2026,11361,arvid_lindblad,32.172727,0.0,1.347159,500.0,29.0,75.0,20.905025,10.868616,15.0
3730,0.100747,2026,11361,colapinto,32.172727,0.0,1.347159,434.0,21.0,62.0,24.166822,13.538731,14.0
3736,-0.300492,2026,11361,bearman,32.172727,0.0,1.347159,970.0,18.0,21.0,36.680214,19.100047,8.0
3732,-0.474141,2026,11361,bortoleto,32.172727,0.0,1.347159,731.0,10.0,16.0,21.346747,11.658173,12.0
3733,-1.067312,2026,11361,hulkenberg,32.172727,0.0,1.347159,993.0,6.0,16.0,21.346747,9.689858,11.0
3737,-1.219711,2026,11361,ocon,32.172727,0.0,1.347159,1668.0,3.0,21.0,36.680214,17.580167,7.0
3734,-1.347456,2026,11361,sainz,32.172727,0.0,1.347159,1667.0,6.0,11.0,33.517307,16.567690,10.0
3738,-1.401442,2026,11361,albon,32.172727,0.0,1.347159,2570.0,5.0,11.0,33.517307,16.949617,6.0
3742,-1.510816,2026,11361,alonso,32.172727,0.0,1.347159,3364.0,3.0,3.0,30.265077,12.060053,2.0
3731,-1.783262,2026,11361,tsunoda,32.172727,0.0,1.347159,1969.0,1.0,75.0,20.905025,11.786960,13.0
3740,-1.946017,2026,11361,bottas,32.172727,0.0,1.347159,2578.0,0.0,0.0,36.211402,19.010015,4.0
3739,-1.946017,2026,11361,perez,32.172727,0.0,1.347159,2809.0,0.0,0.0,36.211402,17.203147,5.0
3741,-2.002409,2026,11361,stroll,32.172727,0.0,1.347159,3436.0,0.0,3.0,30.265077,18.205024,3.0